### ISSUE TITLE
Update the version string of the Rust package, not the dependencies

### ISSUE THREAD

**Issue by majorz** [resin-io/versionist#101]
There can be multiple `version = "..."` entries in both Cargo.toml and Cargo.lock - for the main package and for dependencies as well. We need to change the version string of the package only.

Also update the regex expression for Rust manifest files to support version numbers wrapped in single-quote literal strings.

And narrow the regex replacement to just the .toml and .lock files (not Cargo.*).

**Comment by majorz** [comment]
Oops, there can be multiple `version = "..."` entries in both files - for the main package and for dependencies as well. I will change the title and description of the issue.

**Comment by lurch** [comment]
> And narrow the regex replacement to just the .toml and .lock files (not Cargo.*).

Heh ;-)  https://github.com/resin-io/versionist/pull/97#discussion_r148371165

Hmm, from a little bit of searching, it seems like `Cargo.lock` is broadly similar to `npm-shrinnkwrap.json`.
@jviotti @jhermsmeier @hedss @lekkas  On projects (like Etcher) where we actually use both a `package.json` **and** a `npm-shrinkwrap.json`, and where VersionBot is being used, I guess we need an additional `updateVersion` [preset](https://github.com/resin-io/versionist#updateversion) that would update the version number in both `package.json` and `npm-shrinkwrap.json` at the same time? If this _is_ the case (and I'm not just getting horribly confused?) I'll create a separate `versionist` issue to track this.

**Comment by majorz** [comment]
@lurch +1 for updating `npm-shrinkwrap.json` if exists in the `npm` preset. This should be done for `package-lock.json` as well I think.

**Comment by lurch** [comment]
Cool, created #103 :)

**Comment by lurch** [comment]
This can be closed now, @majorz ?

**Comment by majorz** [comment]
Right, closing it now, thanks!
