### ISSUE TITLE
Could have a `updateQuotedVersion` preset for `updateVersion`

### ISSUE THREAD

**Issue by lurch** [resin-io/versionist#110]
As initially discussed in https://github.com/resin-io/versionist/issues/84#issuecomment-361959222 (so I won't bother copy'n'pasting the info).

This would be a generic 'version-update' mechanism that would work with _any_ type of text file (i.e. it'd be language / framework independent), as long as the version is contained between single-quote `'` or double-quote `"` characters.

And it probably needs a better name than `quotedPatternReplace` :laughing:

**Comment by lurch** [comment]
> And it probably needs a better name than `quotedPatternReplace`

I guess `updateQuotedVersion` might be a good name for this preset?

**Comment by majorz** [comment]
I like `updateQuotedVersion` better.

I have a concern that this will be too powerful for regular users.

Maybe the proper way of adding such a feature is by allowing the users to write their own equivalents of `cargo` and `npm` in the form of plugins where unit tests can be included in the same way we have for the patterns we provide.

And then if we think about that further - the ones we provide like `npm` can be done in the same plugin form themselves. Although living in the same repo.

What do you guys think about that? Or this is too much work to be involved for this stage (I do not have any experience with implementing such thing in JS)?

**Comment by lurch** [comment]
What do you mean by "too powerful for regular users"? Do you mean that it'd just be too hard to use? Do you mean it'll allow them to do things that they "shouldn't" be allowed to do? Or something else?

Yeah I suspect a "plugin" concept is probably too much work at this stage.
BTW I'm hoping to tackle this before Friday (if I get the time) because @hedss has asked for it.

**Comment by majorz** [comment]
Please ignore that part of my comment. I got confused about some of the details.

**Comment by majorz** [comment]
As a different note let's make sure we handle beginning of line and end of line properly with this one if we are not currently doing it. E.g. `__version__ = "1.2.3"` and not `some_prefix__version__ = "1.2.3"`

**Comment by lurch** [comment]
Well the `targetPattern` will just be a regex, so the user is free to use `^` if they want or not :-)  (or was your last comment intended for #112 rather than this issue?)

**Comment by majorz** [comment]
It was intended for this issue. I am using the examples from the other ticket.

If the user provides `targetPattern: 'DISTRO_VERSION = '` or `targetPattern: '__version__\s*=\s*'`, it is the natural expectation for this to not cover 'NEXT_DISTRO_VERSION` or `__private__version__` example definitions.

If we do not enforce beginning of line ourselves, most users of this feature will provide a buggy `targetPattern` that acts as a ticking bomb.

Documenting this clearly and using a `^` in the example we provide will minimize the chance of error, but then how many people will need to write a pattern without `^` - is there a case like that we can think of?

**Comment by majorz** [comment]
While I was looking at the `setup.py` case, I figured a use case could be a function call that has version as an argument, e.g. `setup(name="awesome",  version="1.0.0", ...)`.

Alright, in that case I think we just need to document this as a reminder to the user - to not forget to put `^` for the common use case). Or we can just use `^` in the example we provide for the preset - that will serve as a reminder. (Oh, and we need to fix our own regexes if they have that same problem ;))

**Comment by lurch** [comment]
Okay, so "speccing this out a bit more", I guess we'd could allow something like:
```js
updateVersion: {
    preset: 'updateQuotedVersion',
    workingDir: 'meta-resin-common/conf/distro/include',
    targetFile: 'resin-os.inc',
    regex: '^DISTRO_VERSION\s+=\s+',
    regexFlags: null
}
```

For the `'updateQuotedVersion'` preset, the `targetFile` and `regex` options would be mandatory, and the `workingDir` and `regexFlags` options wuld be optional.
Open to any suggestions or improvements @majorz :-D

**Comment by majorz** [comment]
It is looking awesome! The only thing as discussed in the other ticket is the naming of the `targetFile` argument (because of possible support for multiple files or globs). Other than that, :musical_note:.

**Comment by majorz** [comment]
I was looking at the table with presets on the other ticket - how about if we just use `quoted` instead of `updateQuotedVersion`? We already do `updateVersion {...}` at the level above, and I like the single word approach for all presets more. What do you think?

**Comment by lurch** [comment]
Edited the above comment, if you want to see what it looks like :slightly_smiling_face:

**Comment by majorz** [comment]
Better looking indeed!

**Comment by lurch** [comment]
More updates... :slightly_smiling_face:
