### ISSUE TITLE
Default to internal versionist.conf.js if none is passed

### ISSUE THREAD

**Issue by lekkas** [resin-io/versionist#58]
It might make sense to default to the internal `versionist.conf.js` configuration if none is passed, with the ability to override it with `-c`. This is similar to how `resin-lint` works (https://github.com/resin-io/resin-lint/blob/master/lib/resin-lint.coffee#L9)

**Comment by hedss** [comment]
I think there's an ordering caveat here:
* If the `-c` option exists, use the referenced configuration file
* If no `-c` option, but there is `versionist.conf.js` in the CWD, use that (which is the current default configuration)
* If no `-c` option, and there is no `versionist.conf.js` in the CWD, fallback to the internal configuration

**Comment by lekkas** [comment]
@hedss you're right, this precedence sounds good to me

**Comment by lekkas** [comment]
cheers @craig-mulligan , I'm closing this
