### ISSUE TITLE
Only append date in versions deployed on production

### ISSUE THREAD

**Issue by lekkas** [resin-io/versionist#59]
The current template will add date information on every version bump:

```
template: [
    '## v{{version}} - {{moment date "Y-MM-DD"}}',
    '',
    [...]
```

I'm worried that this will cause confusion in the current, pre-keyframe, transitional period to both developers and the devops team, because the current convention is to add changelog timestamps to mark production deploys. So I suggest we simply drop the timestamp after the version, at least for the first `versionist` iteration. [Edit: improved wording on current status]

**Comment by lurch** [comment]
Sorry, that's my fault https://github.com/resin-io/versionist/pull/44#pullrequestreview-10435279  :wink: 

But (personally) I'd expect the date listed in the Changelog to be the date that version was released, not the date that it was deployed. I'm obviously not familiar with the convention you're referring to, but are you suggesting that when a component gets deployed, somebody goes in and hand-edits the Changlog to add the deployment date?? (and if that _is_ the case, perhaps it should be manually labelled as deployment-date, and not left to be misinterpreted as version-release-date?)

**Comment by brownjohnf** [comment]
@lurch Yes, I manually add deploy dates to the changelogs. The issue is that for our components, deployment *is* release. They're not released until they're deployed.

**Comment by brownjohnf** [comment]
@lekkas I think it's actually okay to leave the date in with the version bump, since I think our interim solution is for me to deploy by tagged docker version. Basically, I'll no longer have anything to do with repos, and only work at the keyframe+docker image level of abstraction. Does that match with your understanding?

**Comment by lurch** [comment]
> Yes, I manually add deploy dates to the changelogs.

Sorry to nit-pick but the changelogs (post-versionist-adoption) say `DO NOT EDIT THIS FILE MANUALLY!` :-/

**Comment by hedss** [comment]
@lurch I don't think your final comment is valid anymore, given Jack's statement above. I'm going to assume we're keeping the version date for now.

**Comment by lekkas** [comment]
> since I think our interim solution is for me to deploy by tagged docker version. Basically, I'll no longer have anything to do with repos, and only work at the keyframe+docker image level of abstraction. Does that match with your understanding

@brownjohnf yes, I'm on the same page here.

@hedss @lurch Yes, since we're going with keyframes from the first iteration we can keep the version date. Thanks for chiming in, I guess I can safely close this issue now! :)
