### ISSUE TITLE
Versionist should be able to update itself with a simple script action

### ISSUE THREAD

**Issue by lekkas** [resin-io/versionist#64]
It'd be nice if we had an easy way , like a `package.json` script, to run `npm run versionist` on this very repo

**Comment by lurch** [comment]
I thought the versionist CHANGELOG was already being updated by versionist itself?

**Comment by lekkas** [comment]
It is, this issue is very low priority since one can just run`./bin/cli.js`

**Comment by lurch** [comment]
Ahh, now I see :)  I didn't realise there wasn't a local `./versionist` command available (i.e. according to the README you need to install versionist globally, before running it for the first time)

**Comment by lekkas** [comment]
;) Yeah it's just that this creates a chicken and egg situation (kind of), where you'd need to run `npm i -g .` to run `versionist` on the `versionist` repo for the latest changes to come into effect. A minor issue really
