### ISSUE TITLE
Error: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by lekkas** [resin-io/versionist#65]
Attempting to run `versionist` without any arguments in the `versinist` repo (commit 7862dd5) produces the following error:

```
Cannot read property 'trim' of null
TypeError: Cannot read property 'trim' of null
    at Function.clean (/usr/local/lib/node_modules/versionist/node_modules/semver/semver.js:266:24)
    at Object.module.exports.updateVersion.npm (/usr/local/lib/node_modules/versionist/lib/presets.js:271:37)
    at apply (/usr/local/lib/node_modules/versionist/node_modules/lodash/lodash.js:499:17)
    at Object.wrapper [as updateVersion] (/usr/local/lib/node_modules/versionist/node_modules/lodash/lodash.js:5383:16)
    at async.waterfall (/usr/local/lib/node_modules/versionist/bin/cli.js:178:26)
    at nextTask (/usr/local/lib/node_modules/versionist/node_modules/async/dist/async.js:5070:14)
    at /usr/local/lib/node_modules/versionist/node_modules/async/dist/async.js:5064:13
    at apply (/usr/local/lib/node_modules/versionist/node_modules/async/dist/async.js:21:25)
    at /usr/local/lib/node_modules/versionist/node_modules/async/dist/async.js:56:12
    at /usr/local/lib/node_modules/versionist/node_modules/async/dist/async.js:840:16
```

This looks like it could be related to that commit missing a change-type entry, but still, it'd be nice if we handled this error case more gracefully

**Comment by lurch** [comment]
I just did a bit of digging into this, and it seems the problem is the `return callback(null, null);` at https://github.com/resin-io/versionist/blob/master/bin/cli.js#L156

Looking at the other usages of the `callback` within that function, I believe that on line 156 the first `null` should actually be an error? Maybe something like:
```javascript
return callback(new Error("No new version number could be generated"), null);
```

**Comment by lekkas** [comment]
I agree that throwing an error looks like the right approach here - I'd only change the message to something that would give a tiny bit more information on what went wrong, so that the user (and especially ones uninitiated to `versionist`) can take corrective action, like:

```javascript
if (_.includes(documentedVersions, version)) {
  console.log(`Omitting: ${version}`);
  return callback(new Error(`No version incrementing commits were found since version ${version}`), null);
}
```

**Comment by craig-mulligan** [comment]
@lekkas shall I amend that commit?

**Comment by lekkas** [comment]
@craig-mulligan no need to, this is a `versionist` bug, it should handle this case more gracefully

**Comment by lurch** [comment]
Yeah, I wasn't sure what to use for the error-message! Now that you've given me an example I'll PR tomorrow :)

**Comment by lekkas** [comment]
@lurch did we have any update on this? Are you taking this on?

**Comment by lurch** [comment]
Sorry, with xmas & new year I'd forgotten about this. I'll put together a PR tomorrow.

**Comment by lurch** [comment]
My apologies for the lack of action on this -  just been too busy with other stuff.
Anybody else is free to take this on instead ;-)

**Comment by lekkas** [comment]
No worries @lurch thanks for the update
