### ISSUE TITLE
'None' change-type suggestion

### ISSUE THREAD

**Issue by lurch** [resin-io/versionist#76]
As discussed in https://github.com/resin-io-modules/resin-procbots/issues/16 it might be useful if `versionist` supported a `change-type: none` footer tag, so that you could indicate that a commit is only doing small "typo" fixes (which don't modify the program behaviour e.g. editing a code-comment), and such a commit should neither bump the version nor add any entries to the Changelog.
Otherwise there's a risk that the Changelog may get polluted with "typo fix" entries, which might dissuade people from bothering to fix typos on the first place?

**Comment by CameronDiver** [comment]
I was literally just about to make this issue myself! I made an inconsequential change to a `package.json`, which doesn't need a change-type at all, but with VersionBot I needed to add one, so...

+1
