### ISSUE TITLE
Versionist removes the trailing newline from package.json

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/versionist#87]
Which is constantly re-added by npm, tending to make the git history a bit uglier.

I noticed we use https://github.com/fczbkk/update-json to write package.json - which doesn't seem to have been updated lately. Should we write our own simple updateJSON function? Or PR into that repo?

**Comment by lurch** [comment]
Looks like #91 (released in v2.11.2) means this can be closed now? Or should this stay open until after #93 has been 'fixed'?

**Comment by hedss** [comment]
It hadn't been published, it has now.
