### ISSUE TITLE
Change-type vs. Signed-off

### ISSUE THREAD

**Issue by cskiraly** [resin-io/versionist#88]
With the default config, Change-type is only accepted if it at the end, i.e. after Signed-off-by.
This is not too intuitive, and I suppose there are clients out there putting Signed-off-by automatically at the end of the commit message.

**Comment by CameronDiver** [comment]
@cskiraly Change-type does not have to be at the end, but it does have to be in "footer", which is defined as the last empty line downwards. If you have:
```
Change-type: minor

Signed-off-by: Cameron Diver <cameron@resin.io>
```
then versionist thinks that the footer is only the signed-off-by part. To remedy this, just remove the newline from before the signed-off line and versionist will happily pick up the change type.

**Comment by cskiraly** [comment]
@CameronDiver, thanks, that makes sense, especially if programs looking at Signed-off-by have a similar interpretation, and e.g. not expect it to be THE single line footer. Is there a definition behind what "footer" means?

**Comment by CameronDiver** [comment]
The footer is defined to be the commit message contents after the last empty line. This means that if there is a line between the signed-off-by and change-type lines, the footer will be parsed as only the signed-off-by line.

**Comment by cskiraly** [comment]
Thanks. In the meantime I've figured out that the original error I have seen was actually due to something else. Thanks for the info, feel free to close the issue.

**Comment by CameronDiver** [comment]
Great, glad your issue is resolved.
