### ISSUE TITLE
Update Cargo.lock if exists side by side with Cargo.toml

### ISSUE THREAD

**Issue by majorz** [resin-io/versionist#96]
A Rust binary executable project will have Cargo.lock side by side with Cargo.toml: http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

We need to modify Cargo.lock in the same way we modify Cargo.toml to support properly Rust binary executable projects, e.g. WiFi Connect.

**Comment by lurch** [comment]
Closing this, as it was added by #97
